"""align canonical indexes

Revision ID: 004_schema_indexes
Revises: 003_scraper_bridge
Create Date: 2026-09-05 13:54:06.280153

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "004_schema_indexes"
down_revision: Union[str, None] = "003_scraper_bridge"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Preserve all public user IDs while matching the ORM's Identity column.
    op.execute("ALTER TABLE users ALTER COLUMN seq DROP DEFAULT")
    op.execute("DROP SEQUENCE users_seq_seq")
    op.execute(
        "ALTER TABLE users ALTER COLUMN seq ADD GENERATED BY DEFAULT AS IDENTITY"
    )
    op.execute(
        "SELECT setval(pg_get_serial_sequence('users', 'seq'), COALESCE((SELECT MAX(seq) FROM users), 1), EXISTS(SELECT 1 FROM users))"
    )
    # Align metadata with the deployed schema; no tables or data are removed.
    op.execute('ALTER INDEX "ix_activity_user" RENAME TO "ix_activity_logs_user_seq"')
    op.execute(
        'ALTER INDEX "ix_ai_history_client" RENAME TO "ix_ai_search_history_client_key"'
    )
    op.execute(
        'ALTER INDEX "ix_birthday_wishes_member" RENAME TO "ix_birthday_wishes_member_id"'
    )
    op.execute('ALTER INDEX "ix_bookmarks_user" RENAME TO "ix_bookmarks_user_seq"')
    op.execute('ALTER INDEX "ix_chat_user" RENAME TO "ix_chat_messages_user_seq"')
    op.execute(
        'ALTER INDEX "ix_chat_reactions_message" RENAME TO "ix_chat_reactions_message_id"'
    )
    op.create_index(op.f("ix_game_scores_game"), "game_scores", ["game"], unique=False)
    op.create_index(
        op.f("ix_game_scores_user_seq"), "game_scores", ["user_seq"], unique=False
    )
    op.execute(
        'ALTER INDEX "ix_game_sessions_user" RENAME TO "ix_game_sessions_user_seq"'
    )
    op.execute(
        'ALTER INDEX "ix_live_sessions_member" RENAME TO "ix_live_sessions_member_id"'
    )
    op.execute(
        'ALTER INDEX "ix_live_sessions_started" RENAME TO "ix_live_sessions_started_at"'
    )
    op.drop_index("ix_members_gen", table_name="members")
    op.drop_constraint("members_slug_key", "members", type_="unique")
    op.drop_index("uq_members_external_id", table_name="members")
    op.drop_index("ix_members_slug", table_name="members")
    op.create_index(op.f("ix_members_slug"), "members", ["slug"], unique=True)
    op.create_index(
        op.f("ix_members_generation"), "members", ["generation"], unique=False
    )
    op.create_unique_constraint("members_external_id_key", "members", ["external_id"])
    op.drop_constraint("news_slug_key", "news", type_="unique")
    op.drop_index("uq_news_source_id", table_name="news")
    op.drop_index("ix_news_slug", table_name="news")
    op.create_index(op.f("ix_news_slug"), "news", ["slug"], unique=True)
    op.create_unique_constraint("news_source_id_key", "news", ["source_id"])
    op.create_index(
        op.f("ix_notifications_user_seq"), "notifications", ["user_seq"], unique=False
    )
    op.drop_index("ix_refresh_tokens_hash", table_name="refresh_tokens")
    op.drop_constraint(
        "refresh_tokens_hash_refresh_token_key", "refresh_tokens", type_="unique"
    )
    op.create_index(
        op.f("ix_refresh_tokens_hash_refresh_token"),
        "refresh_tokens",
        ["hash_refresh_token"],
        unique=True,
    )
    op.execute('ALTER INDEX "ix_reports_message" RENAME TO "ix_reports_message_id"')
    op.execute(
        'ALTER INDEX "ix_schedule_members_schedule" RENAME TO "ix_schedule_members_schedule_id"'
    )
    op.execute(
        'ALTER INDEX "ix_schedule_reminders_user" RENAME TO "ix_schedule_reminders_user_seq"'
    )
    op.drop_index("uq_schedules_source_id", table_name="schedules")
    op.create_unique_constraint("schedules_source_id_key", "schedules", ["source_id"])
    op.execute(
        'ALTER INDEX "ix_sorter_results_user" RENAME TO "ix_sorter_results_user_seq"'
    )
    op.drop_constraint("users_email_key", "users", type_="unique")
    op.drop_constraint("users_user_id_key", "users", type_="unique")
    op.drop_constraint("users_username_key", "users", type_="unique")
    op.drop_index("ix_users_email", table_name="users")
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.drop_index("ix_users_user_id", table_name="users")
    op.create_index(op.f("ix_users_user_id"), "users", ["user_id"], unique=True)
    op.drop_index("ix_users_username", table_name="users")
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.create_index(
        op.f("ix_verification_tokens_hash_token"),
        "verification_tokens",
        ["hash_token"],
        unique=False,
    )


def downgrade() -> None:
    op.execute("ALTER TABLE users ALTER COLUMN seq DROP IDENTITY")
    op.execute("CREATE SEQUENCE users_seq_seq AS bigint OWNED BY users.seq")
    op.execute(
        "ALTER TABLE users ALTER COLUMN seq SET DEFAULT nextval('users_seq_seq')"
    )
    op.execute(
        "SELECT setval('users_seq_seq', COALESCE((SELECT MAX(seq) FROM users), 1), EXISTS(SELECT 1 FROM users))"
    )
    # Align metadata with the deployed schema; no tables or data are removed.
    op.drop_index(
        op.f("ix_verification_tokens_hash_token"), table_name="verification_tokens"
    )
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.create_index("ix_users_username", "users", ["username"], unique=False)
    op.drop_index(op.f("ix_users_user_id"), table_name="users")
    op.create_index("ix_users_user_id", "users", ["user_id"], unique=False)
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.create_index("ix_users_email", "users", ["email"], unique=False)
    op.create_unique_constraint("users_username_key", "users", ["username"])
    op.create_unique_constraint("users_user_id_key", "users", ["user_id"])
    op.create_unique_constraint("users_email_key", "users", ["email"])
    op.drop_index(op.f("ix_sorter_results_user_seq"), table_name="sorter_results")
    op.create_index(
        "ix_sorter_results_user", "sorter_results", ["user_seq"], unique=False
    )
    op.drop_constraint("schedules_source_id_key", "schedules", type_="unique")
    op.create_index("uq_schedules_source_id", "schedules", ["source_id"], unique=True)
    op.drop_index(
        op.f("ix_schedule_reminders_user_seq"), table_name="schedule_reminders"
    )
    op.create_index(
        "ix_schedule_reminders_user", "schedule_reminders", ["user_seq"], unique=False
    )
    op.drop_index(
        op.f("ix_schedule_members_schedule_id"), table_name="schedule_members"
    )
    op.create_index(
        "ix_schedule_members_schedule",
        "schedule_members",
        ["schedule_id"],
        unique=False,
    )
    op.drop_index(op.f("ix_reports_message_id"), table_name="reports")
    op.create_index("ix_reports_message", "reports", ["message_id"], unique=False)
    op.drop_index(
        op.f("ix_refresh_tokens_hash_refresh_token"), table_name="refresh_tokens"
    )
    op.create_unique_constraint(
        "refresh_tokens_hash_refresh_token_key",
        "refresh_tokens",
        ["hash_refresh_token"],
    )
    op.create_index(
        "ix_refresh_tokens_hash", "refresh_tokens", ["hash_refresh_token"], unique=False
    )
    op.drop_index(op.f("ix_notifications_user_seq"), table_name="notifications")
    op.drop_constraint("news_source_id_key", "news", type_="unique")
    op.drop_index(op.f("ix_news_slug"), table_name="news")
    op.create_index("ix_news_slug", "news", ["slug"], unique=False)
    op.create_index("uq_news_source_id", "news", ["source_id"], unique=True)
    op.create_unique_constraint("news_slug_key", "news", ["slug"])
    op.drop_constraint("members_external_id_key", "members", type_="unique")
    op.drop_index(op.f("ix_members_generation"), table_name="members")
    op.drop_index(op.f("ix_members_slug"), table_name="members")
    op.create_index("ix_members_slug", "members", ["slug"], unique=False)
    op.create_index("uq_members_external_id", "members", ["external_id"], unique=True)
    op.create_unique_constraint("members_slug_key", "members", ["slug"])
    op.create_index("ix_members_gen", "members", ["generation"], unique=False)
    op.drop_index(op.f("ix_live_sessions_started_at"), table_name="live_sessions")
    op.drop_index(op.f("ix_live_sessions_member_id"), table_name="live_sessions")
    op.create_index(
        "ix_live_sessions_started", "live_sessions", ["started_at"], unique=False
    )
    op.create_index(
        "ix_live_sessions_member", "live_sessions", ["member_id"], unique=False
    )
    op.drop_index(op.f("ix_game_sessions_user_seq"), table_name="game_sessions")
    op.create_index(
        "ix_game_sessions_user", "game_sessions", ["user_seq"], unique=False
    )
    op.drop_index(op.f("ix_game_scores_user_seq"), table_name="game_scores")
    op.drop_index(op.f("ix_game_scores_game"), table_name="game_scores")
    op.drop_index(op.f("ix_chat_reactions_message_id"), table_name="chat_reactions")
    op.create_index(
        "ix_chat_reactions_message", "chat_reactions", ["message_id"], unique=False
    )
    op.drop_index(op.f("ix_chat_messages_user_seq"), table_name="chat_messages")
    op.create_index("ix_chat_user", "chat_messages", ["user_seq"], unique=False)
    op.drop_index(op.f("ix_bookmarks_user_seq"), table_name="bookmarks")
    op.create_index("ix_bookmarks_user", "bookmarks", ["user_seq"], unique=False)
    op.drop_index(op.f("ix_birthday_wishes_member_id"), table_name="birthday_wishes")
    op.create_index(
        "ix_birthday_wishes_member", "birthday_wishes", ["member_id"], unique=False
    )
    op.drop_index(
        op.f("ix_ai_search_history_client_key"), table_name="ai_search_history"
    )
    op.create_index(
        "ix_ai_history_client", "ai_search_history", ["client_key"], unique=False
    )
    op.drop_index(op.f("ix_activity_logs_user_seq"), table_name="activity_logs")
    op.create_index("ix_activity_user", "activity_logs", ["user_seq"], unique=False)
